version: '3'

#docker-compose -f docker/docker-compose.yml up
services:
  dolar_database:
    build:
      dockerfile: docker/DockerfileDatabase
      context: ../
    environment:
      MYSQL_ROOT_PASSWORD: Cerrito844
  dolar_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - dolar_database
    links:
      - dolar_database
    environment:
      PMA_HOST: dolar_database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "Cerrito844"
    ports:
      - "3034:80"
  dolar_server:
    depends_on:
      - dolar_database
    links:
      - dolar_database:dolar_database
    build:
      dockerfile: docker/DockerfileServer
      context: ../
    volumes:
      - "../:/dolar"
    ports:
      - "3033:3033"
